"""
Enterprise Observability Platform

Component:
    EO-DQ Engine

Module:
    base.py

Description:
    Defines the abstract validator contract for all Enterprise
    Observability Data Quality validators.

Author:
    Enterprise Observability Team

Version:
    1.0.0-alpha
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any


class BaseValidator(ABC):
    """
    Abstract base class for all Enterprise Observability validators.

    Validators must remain:

        - Stateless
        - Source agnostic
        - Thread-safe

    The validation contract supports both record-level and
    dataset-level validation.
    """

    # ------------------------------------------------------------------
    # Validator Metadata
    # ------------------------------------------------------------------

    name: str = "base"

    description: str = "Base validator"

    version: str = "1.0.0-alpha"

    supported_parameters: list[str] = []

    supported_datatypes: list[str] = []

    #
    # record | dataset
    #
    scope: str = "record"

    # ------------------------------------------------------------------
    # Abstract Validation Contract
    # ------------------------------------------------------------------

    @abstractmethod
    def validate(
        self,
        dataset: list[dict[str, Any]] | None = None,
        record: dict[str, Any] | None = None,
        profile: dict[str, Any] | None = None,
        rule: Any = None,
        context: Any = None,
    ) -> Any:
        """
        Validate telemetry data.

        Parameters
        ----------
        dataset

            Complete dataset.

            Used by dataset-level validators.

        record

            Individual telemetry record.

            Used by record-level validators.

        profile

            Dataset profile generated by DatasetProfiler.

            Dataset validators should prefer this over scanning
            the dataset again.

        rule

            Runtime rule.

        context

            Execution context.

        Returns
        -------
        RuleResult
        """

        raise NotImplementedError

    # ------------------------------------------------------------------
    # Helper Methods
    # ------------------------------------------------------------------

    @staticmethod
    def is_null(value: Any) -> bool:
        """
        Returns True if the supplied value should be considered empty.
        """

        if value is None:
            return True

        if isinstance(value, str):
            return value.strip() == ""

        if isinstance(value, (list, tuple, dict, set)):
            return len(value) == 0

        return False

    # ------------------------------------------------------------------

    @staticmethod
    def field_exists(
        record: dict[str, Any],
        field_path: str,
    ) -> bool:
        """
        Returns True if a nested field exists.
        """

        return (
            BaseValidator.get_field_value(
                record,
                field_path,
            )
            is not None
        )

    # ------------------------------------------------------------------

    @staticmethod
    def get_field_value(
        record: dict[str, Any],
        field_path: str,
        default: Any = None,
    ) -> Any:
        """
        Returns a nested field value.

        Supports dot-separated paths.

        Example

            resource.attributes.service.name
        """

        current: Any = record

        for part in field_path.split("."):

            if not isinstance(current, dict):
                return default

            if part not in current:
                return default

            current = current[part]

        return current

    # ------------------------------------------------------------------

    @staticmethod
    def ensure_record(
        record: dict[str, Any] | None,
    ) -> dict[str, Any]:
        """
        Ensure a record is available.
        """

        if record is None:
            raise ValueError(
                "Record cannot be None for a record validator."
            )

        return record

    # ------------------------------------------------------------------

    @staticmethod
    def ensure_dataset(
        dataset: list[dict[str, Any]] | None,
    ) -> list[dict[str, Any]]:
        """
        Ensure a dataset is available.
        """

        if dataset is None:
            raise ValueError(
                "Dataset cannot be None for a dataset validator."
            )

        return dataset

    # ------------------------------------------------------------------

    @staticmethod
    def ensure_profile(
        profile: dict[str, Any] | None,
    ) -> dict[str, Any]:
        """
        Ensure a dataset profile is available.
        """

        if profile is None:
            raise ValueError(
                "Dataset profile has not been supplied."
            )

        return profile

    # ------------------------------------------------------------------

    @classmethod
    def metadata(cls) -> dict[str, Any]:
        """
        Returns validator metadata.
        """

        return {

            "name": cls.name,

            "description": cls.description,

            "version": cls.version,

            "scope": cls.scope,

            "supported_parameters": cls.supported_parameters,

            "supported_datatypes": cls.supported_datatypes,
        }

    # ------------------------------------------------------------------

    def __repr__(self) -> str:

        return (
            f"{self.__class__.__name__}"
            f"(name='{self.name}', "
            f"scope='{self.scope}', "
            f"version='{self.version}')"
        )