# =============================================================================
# Enterprise Observability Runner Configuration
# =============================================================================

environment: dev

telemetry:

  signal: logs

  domain: infrastructure
# -----------------------------------------------------------------------------
# Input Configuration
# -----------------------------------------------------------------------------
input:

  type: local          # local | s3

  local:
    root: samples/raw

  s3:
    bucket: itx-dwy-eo-dataquality-905417995456-us-east-1-an
    prefix: raw

# -----------------------------------------------------------------------------
# Output Configuration
# -----------------------------------------------------------------------------
output:

  type: local          # local | s3

  local:
    root: reports

  s3:
    bucket: itx-dwy-eo-dataquality-905417995456-us-east-1-an
    prefix: reports

# -----------------------------------------------------------------------------
# DQ Engine
# -----------------------------------------------------------------------------
dq_engine:
  
  runtime_file: eo_dq_engine/config/dq_rules.yaml

# -----------------------------------------------------------------------------
# AWS
# -----------------------------------------------------------------------------
aws:

  region: us-east-1